services:
  - type: web
    name: spintocountry-backend
    env: docker
    plan: free
    healthCheckPath: /healthz
    dockerfilePath: apps/backend/Dockerfile   
    buildContext: .                      
    envVars:
      - key: DATASTORE_PROVIDER
        value: csv
      - key: DATA_FILE_PATH
        value: /app/data/sample.csv
      - key: LOG_LEVEL
        value: INFO
      # Derives CORS origin from this URL's origin
      - key: FRONTEND_BASE_URL
        value: https://gilzeevi25.github.io/4RotationalForce
      # Optional JSON list of extra origins
      # - key: ALLOWED_ORIGINS
      #   value: '["https://example.com"]'
      # Allow vite localhost origins during dev if you expose the container
      - key: DEV_INCLUDE_LOCALHOST
        value: "false"
